### ISSUE TITLE
Running this script only got message created by function usageErr

### ISSUE THREAD

**Issue by bennybhlin** [cybersecurityops/cyber-ops-with-bash#2]
Dear authors:
 Greeting. Sorry to ask question in this way. My name is Benny Lin, and I am now translating this book (Cybersecurity Ops with bash), hence I am verifying all sample codes & add comments when I thought it's necessary.

 For example 10-3, I copied codes from GitHub then paste to my Git bash environment to test it. What I found is, no matter I provided starting directory or not (with option -d, such as ./baseline.sh -d / before.txt), the result is always error messages from function usageErr.

 I tried to add a line below, right before shift command:

    echo "Check all options inside parseArgs before shifted: $OPTARG, $OPTIND"
    
But when I ran './baseline.sh -d / before.txt' again, the output became:

    Check all options inside parseArgs before shifted: ,1
    
It seems that $OPTARG wan empty, and $OPTIND was 1. I wonder: aren't $OPTARG and $OPTIND global variables?  Shouldn't they be valid while inside a function being called?

So I  added another line before calling parseArgs function:

    echo "Before parseArgs runs: $#,$0,$1,$2,$3"

Then I ran './baseline.sh -d / before.txt' again, I could see output like this:

    Before parseArgs runs: 3,./baseline.sh,-d,/,before.txt,,1

So before parseArgs was called by script, the script itself did recognize my 3 options (-d, /, and before.txt).

 Then I suddenly realized, regarding $# inside a function, does it represent function's number of options? Or it actually represents script's number of options? Because if it IS function's number of options, then it would always be '0', so parseArgs would always call usageErr, so I always got the error message.

    Please provide your comments. I really love to discuss with authors while I translated.

**Comment by cybersecurityops** [comment]
Thank you for pointing this out.  The code file has been corrected.
